### PR TITLE
New JSDOC layout

### PR DESCRIPTION
**Pull request by zarov**
As explained in #911 I wrote a new jsdoc layout. The result is visible here https://zarov.github.io/itowns/docs/out/

Three commits in this PR:
- a first one to move the documentation from `API_Doc` to `docs`, giving a more explicit URL
- a second with the implementation of the new layout
- a third with some update in the current documentation

There is still things to do, but I feel that this implementation is sufficiently advanced to start pushing it now.

### CODE REVIEW

**Comment by jailln** [comment]
Thanks for this work, the documentation is much easier to read this way.

Just one remark: There is remaining references to Providers ([at least in the Scheduler](https://zarov.github.io/itowns/docs/out/#api/Base/Scheduler)) in the doc (and in the code). They should be replaced by Sources ?

**Comment by zarov** [comment]
Thanks ! Yes `Providers` are still present, as they are going deprecated but still used for some usecases (3dtiles, pointcloud...). Concerning the documentation, I would let them but I could at least generate correctly the documentation of the `Provider` interface.

**Comment by mbredif** [comment]
That looks very good !
some quick remarks
- the tutorials could have a disclaimer about the geoportail key usage restriction or use a key-less ogc source (maybe as an alternative).
- the following keywords yield nothing : pointcloud, potree, 3dtiles (or variations), mapbox

**Comment by zarov** [comment]
> the tutorials could have a disclaimer about the geoportail key usage restriction or use a key-less ogc source (maybe as an alternative).

If you have some alternative I'm for it, otherwise I'll put a disclaimer.

> the following keywords yield nothing : pointcloud, potree, 3dtiles (or variations), mapbox

That's normal, the search is not a search, but a filter in the current menu: it doesn't search inside the documentation. This feature is for later, because more complex to handle in a static website.

**Review by nosy-b — APPROVED** [review]
Nice!
Agreed with @mbredif remarks but that's already an improvement

**Comment by zarov** [comment]
Thanks ! I know there is still some documentation to update, but I suggest to open other PRs to do it and quickly close this one to see those updates in the new layout.

**Pull request merged**
