### PR TITLE
fix (examples): Wrong zoom min in layer example

### LINKED ISSUE #600: Some layers prevent subdivision on globe
## Your Environment

* Version used: current master
* Browser Name and version: Chromium and Firefox (latests) on Linux

## Context

The new denomination layer sometimes prevent subdivision on globe. Here is a gif of the process:
peek 2017-12-12 20-13

## Steps to Reproduce (for bugs)

1.  `npm start` and load the root `index.html`
1.  check Layer globe > Show tiles
1.  zoom on paris 
1.  check and uncheck the Denomination layer

## Expected Behavior
 the subdivision doesn't change (because there are other layers with textures)

## Actual Behavior
When Denomination is active, it de-subdivises tiles.

### PR DESCRIPTION
**Pull request by gchoqueux**
remove error network WMTS

### CODE REVIEW

**Comment by gchoqueux** [comment]
~update:  to fix totally  #600, it needs PR #583~

**Comment by autra** [comment]
>  it needs PR #583

Can you explain why? From the tile of #583, it is not obvious.

**Comment by gchoqueux** [comment]
@autra because we exceed the max count color layers allowed in itowns

**Comment by autra** [comment]
So this issue does not help for #600, right? (I'm not against it, just wondering)

**Comment by gchoqueux** [comment]
@autra yes, it doesn't fix #600

**Review by autra — APPROVED** [review]
LGTM, thanks :-)

**Pull request merged**
