### PR TITLE
refactor(TiledGeometryLayer): remove uncessary setting.

### PR DESCRIPTION
**Pull request by gchoqueux**
## Description
Remove unnecessary setting.

#2030 re-open

### CODE REVIEW

**Review by jailln — APPROVED** [review]

**Comment by jailln** [comment]
@gchoqueux what is the status of this PR ?

**Comment by gchoqueux** [comment]
@jailln unfortunately, I don't have the time to work on it

**Comment by jailln** [comment]
@gchoqueux it's not ready to be merged?

**Comment by gchoqueux** [comment]
tests don't pass

**Comment by jailln** [comment]
I just ran them locally and they pass. The log of the failed github action has expired and I cannot rerun it; can you push an empty commit or rebase so they re-run please ?

**Pull request closed without merging**
