### PR TITLE
Improve globe

### PR DESCRIPTION
**Pull request by peppsac**
This PR has 2 small fix/feature commits:

- make sure init node function is called for level 0 nodes (currently it's only called on level >= 1)
- replace the hardcoded *no-texture* color by a configurable one (but the default is still "Blue Ocean")

And updates the `multiglobe` example:
multiglobe

### CODE REVIEW

**Review by gchoqueux — COMMENTED** [review]
looks nice in first reading

**Comment by gchoqueux** [comment]
LGTM

I don't understand why culling doesn’t work between the globes

visible

**Comment by peppsac** [comment]
I'll working on a fix for the (horizon) culling issue.

**Comment by peppsac** [comment]
Fixed

**Review by gchoqueux — APPROVED** [review]
Ok

**Pull request merged**
