### PR TITLE
Turn on ESLint valid-jsdoc rule (as warning for now)

### PR DESCRIPTION
**Pull request by tbroyer**
Don't require descriptions for parameter and return tags:
type matters most, and description can sometimes be redundant
and useless, making it annoying and noisy.

#314

### CODE REVIEW

**Comment by vcoindet** [comment]
SGTM.

In our case, it returns a lot of warning as we put some jsdoc syntax in some files that won't appear in the final doc... maybe these should be just normal comments to avoid these warnings.

**Comment by tbroyer** [comment]
> maybe these should be just normal comments to avoid these warnings.

or fixed? ;-)

**Comment by autra** [comment]
> descriptions for parameter and return tags:
type matters most

I disagree with this, especially in js. Often, a good js code is one where type is either so evident it's not worth mentioning, or where it does not really matter. Ok, sometimes you need to be precise about it, but let's not make it compulsory. If we want a typed language, let's use typescript :-)

Btw I'm actually tempted to try esdoc instead of jsdoc for its ability to infer these types (I need to check the extent of this ability though).

Also, I disagree with the very principle of warnings, especially when it generates so many of them. By experience, they will never get corrected and *will* get ignored. To me, it's error or nothing. This politics would also have the nice side-effect of not putting the burden on other devs, especially the one who has nice enough to correct them (I'm speaking about me there, I have corrected enough eslint problem to have a say on this :-) )

**Comment by autra** [comment]
> or fixed? ;-)

You've said it.

**Comment by vcoindet** [comment]
yeah it can be fixed too, I will correct them in a new PR ! ;)

**Comment by tbroyer** [comment]
> To me, it's error or nothing. […] (I'm speaking about me there, I have corrected enough eslint problem to have a say on this :-) )

OK, let's do that: I'll fix the jsdoc comments / make them non-jsdoc and update the rule to `'error'`.

**Comment by vcoindet** [comment]
OK, so I'll let you take care of it

**Comment by tbroyer** [comment]
Forgot to respond to this comment:

> I disagree with this, especially in js. Often, a good js code is one where type is either so evident it's not worth mentioning, or where it does not really matter. Ok, sometimes you need to be precise about it, but let's not make it compulsory. If we want a typed language, let's use typescript :-)

It's not about us, it's about our users.

I'd be OK with switching from `valid-jsdoc` to the `eslint-plugin-jsdoc` which allows not requiring parameter types (https://www.npmjs.com/package/eslint-plugin-jsdoc#eslint-plugin-jsdoc-rules-require-param-type).

**Review by gchoqueux — APPROVED** [review]
Thanks

**Comment by gchoqueux** [comment]
Rebase and I merge

**Comment by autra** [comment]
thanks @tbroyer

**Pull request merged**
