### PR TITLE
Update to threejs r152

### PR DESCRIPTION
**Pull request by ketourneau**
## Description

We try to use iTowns in our project with another viewer which use threejs r152.

So we need to update iTowns to threejs r152 to use it.

### CODE REVIEW

**Comment by jailln** [comment]
Hi, thanks for this contribution :) 
It's actually already ongoing in #1977 (where we update all itowns dependencies) and it should be merged pretty soon. I'll leave it open for now in case #1977 takes too long and we want to merge this first.

**Comment by gchoqueux** [comment]
hello
you could just pick this PR commit [30edef65961fb61f8ecab216ee2125e9eeb892ec](https://github.com/iTowns/itowns/pull/1977/commits/30edef65961fb61f8ecab216ee2125e9eeb892ec)
and @mgermerie will remove this commit from his PR

**Comment by jailln** [comment]
> hello you could just pick this PR commit [30edef65961fb61f8ecab216ee2125e9eeb892ec](https://github.com/iTowns/itowns/pull/1977/commits/30edef65961fb61f8ecab216ee2125e9eeb892ec) and @mgermerie will remove this commit from his PR

Yes, and this one too: 738f5ae5459260ad720959dcd259de78da0f5136

**Comment by ketourneau** [comment]
I created new MR with correct version name : https://github.com/iTowns/itowns/pull/2127

**Pull request closed without merging**
