### PR TITLE
Unify errors in `view.addLayer`

### PR DESCRIPTION
**Pull request by autra**
## Description

This commit make it so that view.addLayer don't throw anything anymore, and uses promise rejection instead, for a cleaner API.

## Motivation and Context

`view.addLayer` currently throws some errors, and some others (preprocessing failure for instance) are handled by a promise rejection. This is confusing for users, and forces them to use 2 different error handling mechanism, see indirectly #768.

I've added a BREAKING CHANGE in my commit message to be completely on the safe side of things, but I don't expect this change to hurt anyone.

This PR benefits from adding `?w=1` in the url :-)

### CODE REVIEW

**Comment by autra** [comment]
@iTowns/reviewers please r?

**Comment by autra** [comment]
Arf, the github "update" button doesn't do what I thought it will do, rebasing now.

**Review by zarov — COMMENTED** [review]
Don't forget to update the documentation ! LGTM otherwise

**Comment by autra** [comment]
@zarov done for the documentation, even though I'm not sure whether or not this should be mentioned. I guess it doesn't hurt...

**Review by zarov — APPROVED** [review]

**Pull request merged**
