### PR TITLE
Resize listener is referenced to remove it at dispose

### PR DESCRIPTION
**Pull request by valentinMachado**
## Description
In View class the resize listener is referenced, to remove it at dispose

## Motivation and Context
This change allow to well dispose a View, and to allow GC to collect View disposed.

### CODE REVIEW

**Comment by jailln** [comment]
Thanks! Does this solves #1936 ? Have you compared memory snapshots before and after removing the view before and after your changes?

**Review by jailln — APPROVED** [review]

**Comment by valentinMachado** [comment]
> Thanks! Does this solves #1936 ? Have you compared memory snapshots before and after removing the view before and after your changes?

I don't know but before this change when a view was disposed the resize listener was still called, meaning the view was still referenced and thus not garbage collected (meaning everything referenced by the view such as layers I guess was not garbage collected, it could solves #1936 or be part of the fix).

In our use case https://github.com/VCityTeam/UD-Imuv we are creating and disposing many PlanarView, what point me this issue was that after some create/dispose a warning was pointing that there were too many webgl context created. 

I am still going to investigate this and will check memory snapshot after many create/dispose of a view (https://github.com/VCityTeam/UD-Imuv/issues/410).

**Comment by jailln** [comment]
It doesn't fixes #1936 but it is still a good fix. Can you rename your commit to follow the [angular convention](https://github.com/bcoe/conventional-changelog-standard/blob/master/convention.md) please ? Then we can merge

**Comment by valentinMachado** [comment]
> It doesn't fixes #1936 but it is still a good fix. Can you rename your commit to follow the [angular convention](https://github.com/bcoe/conventional-changelog-standard/blob/master/convention.md) please ? Then we can merge

it would have been too simple ^^
done :)

**Pull request merged**
