### PR TITLE
Release v2.3.0.

### PR DESCRIPTION
**Pull request by gchoqueux**
Bumping version for release

@iTowns/reviewers

### CODE REVIEW

**Review by autra — APPROVED** [review]
Good for me :-)

**Comment by gchoqueux** [comment]
We stop the merges for until tomorrow morning to verify the stability of this release v2.3.0

**Comment by peppsac** [comment]
Maybe we should fix #642 before releasing  a new version.

**Comment by gchoqueux** [comment]
I'll fix #642

**Comment by peppsac** [comment]
> I'll fix #642

Then maybe it'll make sense to wait for this fix before freezing master.
We could at least merge the non-api breaking PR like #667, #659, #665.

**Comment by gchoqueux** [comment]
#642 is fixed
#665 could break the api

**Comment by autra** [comment]
>  #665 could break the api

Just passing by, currently it's not.

**Pull request merged**
