### PR TITLE
[WIP] test offline with node

### PR DESCRIPTION
**Pull request by vmora**
run with `node dist/itowns2_test.js`

@tbroyer can you plz try that out and help me on the webpack config. I have build issues:

```
%webpack
Hash: 9199c0a748bf691aec21feee08aee55d96c17109
Version: webpack 1.13.1
Child Library:
    Hash: 9199c0a748bf691aec21
    Version: webpack 1.13.1
    Time: 11096ms
             Asset     Size  Chunks             Chunk Names
        itowns2.js   2.3 MB       0  [emitted]  main
    itowns2.js.map  2.79 MB       0  [emitted]  main
        + 157 hidden modules
Child Test:
    Hash: feee08aee55d96c17109
    Version: webpack 1.13.1
    Time: 11063ms
                  Asset     Size  Chunks             Chunk Names
        itowns2_test.js  2.35 MB       0  [emitted]  main
    itowns2_test.js.map  2.85 MB       0  [emitted]  main
        + 166 hidden modules

    WARNING in ./~/bindings/bindings.js
    Critical dependencies:
    76:22-40 the request of a dependency is an expression
    76:43-53 the request of a dependency is an expression
     @ ./~/bindings/bindings.js 76:22-40 76:43-53

    WARNING in ./~/bindings/README.md
    Module parse failed: /home/vmo/itowns2/node_modules/markdown-loader/index.js!/home/vmo/itowns2/node_modules/bindings/README.md Unexpected token (1:0)
...
    ERROR in ./src/test.js

    /home/vmo/itowns2/src/test.js
      15:1  error  'process' is not defined  no-undef
      33:1  error  'process' is not defined  no-undef
      36:1  error  'process' is not defined  no-undef

    ✖ 3 problems (3 errors, 0 warnings)
```

and when I run the test:

```
node dist/itowns2_test.js

/home/vmo/itowns2/dist/itowns2_test.js:4804
      throw err
            ^
Error: Could not locate the bindings file. Tried:
 → /home/vmo/itowns2/build/webgl.node
 → /home/vmo/itowns2/build/Debug/webgl.node
 → /home/vmo/itowns2/build/Release/webgl.node
...
```

they seem related, the `webgl.node` file is in `node_modules/gl/build/Release/webgl.node`

### CODE REVIEW

**Comment by tbroyer** [comment]
I'd been working yesterday (finishing up this morning; I spent way too many time tracking a small typo in my code :-/ ) on running tests in browsers through Karma (see the `in-browser-test` branch)

The test runs, but currently fails for reasons I may not be able to debug easily:

``` js
        this.viewerDiv = document.createElement('div');
        document.body.appendChild(this.viewerDiv);
        this.globe = new ApiGlobe();
        this.globe.createSceneGlobe(initCenter, this.viewerDiv);
        this.viewerDiv.addEventListener('globe-loaded', function() {
            done();
        });
```

This times out, the event is never dispatched. Any idea? (note: I also tried giving a size to the `div`, didn't change anything)

I also need to update the documentation and the Travis configuration (to have a way to exclude tests that require webgl) so this is not yet ready for a PR.

I'll have a look at using headless-gl (I had that on my todo list too); maybe I'll just rewrite the test using headless-gl and jsdom.

**Comment by tbroyer** [comment]
Wrt your `process` not defined errors, this is ESLint complaining, because `process` is a Node-specific global and ESLint is not configured to recognize this environment.

I strongly believe a testing framework (such as Mocha) will _scale_ better though.

**Comment by vmora** [comment]
@tbroyer I have some work in progress, with a gl context and a test that's actually doing something in the  `wip_offscreen_test` branch

**Comment by vmora** [comment]
I'm able to save an actual image in the [wip_offscreen_test](https://github.com/iTowns/itowns2/tree/wip_offscreen_test) branch (with nodejs 6.2.2)

test

**Comment by peppsac** [comment]
FWIW I've updated the `wip_offscreen_test` branch.
This is the current status:
screnshot

**Comment by peppsac** [comment]
Closing for now.
all: feel free to reopen if you intend to continue this work.

**Pull request closed without merging**
