### PR TITLE
Ecma script 2016

### PR DESCRIPTION
**Pull request by gchoqueux**
up to Ecma script 2016

### CODE REVIEW

**Comment by zarov** [comment]
Beside `**` and `includes`, could you provide a list of things we could update ?

**Comment by gchoqueux** [comment]
@zarov see #943

**Review by zarov — APPROVED** [review]
You forgot some places:
- `Array.prototype.indexOf` in `View`
- `Math.pow` in `PlanarLayer`

Otherwise it's good

**Comment by gchoqueux** [comment]
@zarov  thanks.
I don't remove `indexOf` in view because index  is used to `splice`.

**Pull request merged**
