### PR TITLE
Splitted rendering example

### PR DESCRIPTION
**Pull request by peppsac**
This PR add a new example based on issue #357:

split

### CODE REVIEW

**Comment by peppsac** [comment]
Ping @nosy-b

**Review by nosy-b — CHANGES_REQUESTED** [review]
Looks good! But OpenSM looks like mixed with white, it's too enlightened. 
Has to do with the frag shader when mixing diffuseColor and layerColor maybe?

**Comment by peppsac** [comment]
The rendering looks identical to this layer original site (original on the top of the screenshot):
capture d ecran de 2017-07-28 16-00-50

Note that I changed the OPENSM layer url since the oold one wasn't working anymore.

**Comment by nosy-b** [comment]
My bad, it's just a light OSM rendering and my screen sucks :)
splitcalib

**Review by nosy-b — APPROVED** [review]

**Pull request merged**
