### PR TITLE
fix (ellipsoid) : error longitude in compute Cartesian to Cartographic

### PR DESCRIPTION
**Pull request by gchoqueux**
Fix error in #246

### CODE REVIEW

**Comment by gchoqueux** [comment]
@nosy-b ?

**Comment by nosy-b** [comment]
Ok, but as this function can be used many time to convert arrays of coordinates, should we try to optimize it a bit using factorization?
`e*e` is computed 5 times for example

**Comment by gchoqueux** [comment]
updated
and add fix on wrong ellipsoid size

**Comment by gchoqueux** [comment]
@nosy-b 
updated
and add fix on wrong ellipsoid size

**Review by nosy-b — APPROVED** [review]
I tested using an external converter for Cartesian to Geodetic and reverse, that sounds good.

**Pull request merged**
