### PR TITLE
Geoid rebase

### PR DESCRIPTION
**Pull request by nguyenign**

### CODE REVIEW

**Comment by gchoqueux** [comment]
Warning, there's a problem, this branch isn't rebased on the master branch

**Comment by nguyenign** [comment]
@gchoqueux  i did rebase on master branch, in my fork i see it is on head of master branch. How do you know it is not rebase on master?

**Comment by autra** [comment]
@nguyenign you need to merge your `nguyenign:geoid_rebase` branch into `itowns:master`. Here you're trying to merge it into `itowns:geoid_rebase`. That's why you have that many commits. Please reopen your PR against master.

**Comment by tbroyer** [comment]
Did you know you can change the "base" of a PR without opening a new one? ;-)
https://help.github.com/articles/changing-the-base-branch-of-a-pull-request/

Just did it here; ~~I'll let you reopen if things look OK.~~ (**edit:** it does not; but now you can rebase/clean locally and just (force) push the branch again, rather than open a new PR)

**Comment by autra** [comment]
I didn't, thanks @tbroyer !

**Comment by qdnguyen** [comment]
thank @tbroyer !

but i just make a new PR for geoid examples , we dont need to reopen this pr!

**Pull request closed without merging**
