### PR TITLE
feat(WMTS): Support vendor specific parameters

### LINKED ISSUE #2027: WMTS Source and vendor specific attributes
## Your Environment

* Version used: any
* Browser Name and version: any
* Operating System and version (desktop or mobile): any
* Link to your project: https://www.telecense.com

## Context
WMTS sources are not accepting vendor specific values as WMS Sources

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Expected Behavior
Same as WMS Sources : hability to add vendorSpecific attributes.

## Actual Behavior
vendorSpecific attributes are not accepted

## Possible Cause/Fix/Solution
Put inside WMTS Source the same code as WMS Source. 

After line 88  

this.vendorSpecific = source.vendorSpecific;
        for (const name in this.vendorSpecific) {
            if (Object.prototype.hasOwnProperty.call(this.vendorSpecific, name)) {
                this.url = `${this.url}&${name}=${this.vendorSpecific[name]}`;
            }
        }

### PR DESCRIPTION
**Pull request by mbenevole**
Authorize vendorSpecific attributes as in WMSSources

Closes  #2027 

## Motivation and Context
Same possibilities as WMSSources to enable vendor specific attributes

### CODE REVIEW

**Comment by jailln** [comment]
Thanks! Could you please:
- fix the trailing space problem detected by the linter: https://github.com/iTowns/itowns/actions/runs/4403648916/jobs/7713051988
- rename your commit to something following the [Angular Convention](https://github.com/bcoe/conventional-changelog-standard/blob/master/convention.md). For instance: `feat(WMTS): Support vendor specific parameters`
- add the documentation about these new parameters, like in [WMSSource](https://github.com/iTowns/itowns/blob/master/src/Source/WMSSource.js#L36)
- Add your name to the [Contributors](https://github.com/iTowns/itowns/blob/master/CONTRIBUTORS.md) of itowns :)

**Comment by jailln** [comment]
Is this standard or is there a documentation about these parameters? I found one for WMS (https://docs.geoserver.org/latest/en/user/services/wms/vendor.html) but not for WMTS

**Comment by mbenevole** [comment]
Hi,

 

WMS serves map data as a single image which is rendered on an ad hoc bases, while WMTS serves map data as a set of tiles.

 

Vendor Specific parameters could just help to send additional information to specific implementations of WMS/WMTS servers : geoserver (your doc), but as well qgisserver, …

 

Regards

Michel BÉNET
Tél : +33 (0)9 74 98 15 83


 <http://www.diginove.com/> 

4, rue du Mahatma Gandhi
Espace Beauvalle – Bât. B
13090 Aix-en-Provence
 

 

 

De : Jaillot Vincent ***@***.*** 
Envoyé : jeudi 23 mars 2023 14:19
À : iTowns/itowns ***@***.***>
Cc : Michel BENET ***@***.***>; Author ***@***.***>
Objet : Re: [iTowns/itowns] feat(WMTS): Support vendor specific parameters (PR #2028)

 

Is this standard or is there a documentation about these parameters? I found one for WMS (https://docs.geoserver.org/latest/en/user/services/wms/vendor.html) but not for WMTS

**Comment by jailln** [comment]
Ok thanks, I made the modifications and added a test. I'll let @mgermerie review

**Review by mgermerie — APPROVED** [review]

**Pull request merged**
