### PR TITLE
feature: handle missing WebGL support gracefully

### PR DESCRIPTION
**Pull request by peppsac**
Print a webgl failure message instead of a white screen.

### CODE REVIEW

**Comment by gchoqueux** [comment]
Can you add links?

* test browser support : http://webglreport.com/?v=1
* blacklist card : https://www.khronos.org/webgl/wiki/BlacklistsAndWhitelists
* and comment : Try Firefox and Chrome

**Comment by peppsac** [comment]
Done (except for the 1st link because it's mostly a duplicate of http://get.webgl.org)

**Comment by gchoqueux** [comment]
ok

**Review by gchoqueux — APPROVED** [review]
ok

**Pull request merged**
