### PR TITLE
Layer update strategies

### PR DESCRIPTION
**Pull request by peppsac**
Based on PR #176 

Implement different (and configurable) update strategies for layer.

### CODE REVIEW

**Comment by gchoqueux** [comment]
The tile refinement is too important and this capture there aren't stop queries.

capture du 2016-08-08 16-07-43

**Comment by gchoqueux** [comment]
2 images with little zoom change : 
- image 01 : for selected tile -> tile.level = 18 and elevation.level = 7
- image 02 : for selected tile -> tile.level = 15 and elevation.level = 14

The tile in image 01 should have a elevation.level = 14. (same problem in #176)

Image 01 :


image 02

**Comment by gchoqueux** [comment]
In this capture , the tiles are very too small.
capture du 2016-08-09 14-46-13

**Comment by Jeremy-Gaillard** [comment]
Tested the PR, I did not see any obvious behaviour changes.

**Comment by peppsac** [comment]
Closing: I'll open a new PR when ready (first PR #176 needs to be merged)

**Comment by gchoqueux** [comment]
No updating/reloading when a layer going from invisible to visible

**Pull request closed without merging**
