### PR TITLE
Use newer version of dat.gui

### PR DESCRIPTION
**Pull request by autra**
Now it is installable from github. No need to pass through npm.

@iTowns/reviewers please r?

### CODE REVIEW

**Comment by autra** [comment]
Closing this for now, as apparently the npm config of dat.gui does not work with node 8 (depends on a node-sass version that does not work with node 8 yet).

I might just copy dat.gui.min.js somewhere in the code then :-/

**Comment by autra** [comment]
Reopening as it seems the issue will get fixed. I will forget if I leave that closed. Don't merge now :-)

**Comment by autra** [comment]
To track: https://github.com/sass/node-sass/issues/1985

**Comment by autra** [comment]
@mbredif why did you assign @dgricci here? It looks like a mistake, so I'm assigning myself. Don't hesitate to revert (and explain why) if I missed something.

**Comment by gchoqueux** [comment]
There is still no longer slider for opacity?
Like speed in this [example](https://workshop.chromeexperiments.com/examples/gui/#1--Basic-Usage)

**Comment by autra** [comment]
@gchoqueux I want to update dat.gui for this very reason.

**Comment by gchoqueux** [comment]
cool
Rebase please
and I will merge

**Comment by autra** [comment]
Updated, but I'm hesitating... The problem:

`dat.gui` depends on `sassify` which in turns depends on `node-sass`3.8. There's prebuilt binary for it for node 6 (and `npm install` downloads them), but for node 8, there is no pre-built binary for node-sass 3.8. So `npm install` build it. The problem is that it is very long (ok that'll happen only the first time, but still). 

To fix this, sassify would need to update to node-sass 4, and *then* dat.gui would need to update sassify. Regarding the fact that the last sassify commit was nearly a year ago, that's unlikely to happen soon... All  of that for a bit of UI for debug purpose...

Possible solutions:
- live with it
- push upstream to make things change
- embed dat.gui.js directly in examples/
- other solution ?

**Comment by peppsac** [comment]
Given that `dat.gui.min.js` is only 50KB I'm fine with copying it directly to examples and remove the dat.gui npm module.

**Comment by autra** [comment]
@iTowns/reviewers please r?

**Review by peppsac — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
