### PR TITLE
fix(PointCloud): correct some issues after refacto #2262

### PR DESCRIPTION
**Pull request by AnthonyGlt**
## Description
Correct some issues links to the merge [#2262](https://github.com/iTowns/itowns/pull/2262)

## Motivation and Context
After the merge, there is spam of warnings in the console.
Also the classification wasn't showing anymore in the example view_3d_map.html

## Screenshots
Screenshot from 2024-03-28 18-00-34

Screenshot from 2024-03-28 17-50-31

### CODE REVIEW

**Comment by AnthonyGlt** [comment]
Maybe we could rename `classification` to  `classificationScheme` in the layer options

**Comment by Desplandis** [comment]
@AnthonyGlt Seems that our testing is not efficient to detect such issues. Could you add a unit and/or functional test in this PR to detect similar issues on 3DTiles point clouds?

**Comment by airnez** [comment]
Please also update this comment
https://github.com/iTowns/itowns/blob/f3f8a0a5387a4905a742a0c89a3e8aaba7278d8b/src/Layer/C3DTilesLayer.js#L98

**Comment by AnthonyGlt** [comment]
Also remove ` ; ` in https://github.com/iTowns/itowns/blob/f3f8a0a5387a4905a742a0c89a3e8aaba7278d8b/src/Renderer/PointsMaterial.js#L72

**Review by ftoromanoff — APPROVED** [review]

**Pull request merged**
