### PR TITLE
fix(tooltip): display all properties of a feature

### PR DESCRIPTION
**Pull request by zarov**
Before, only a few selected properties of a feature were displayed in
FeatureToolTip. Now, everything is displayed.
In the same time, a quick cleaning has been done, and the FeatureToolTip
has been added to the shapefile example.

### CODE REVIEW

**Review by gchoqueux — COMMENTED** [review]
You should add a filter callback, there are too much displayed informations.
it would be necessary that the example globe vecto should be similar to the previous version.

**Comment by zarov** [comment]
I updated `FeatureToolTip`, added some documentation and simplified its usage.

**Review by gchoqueux — COMMENTED** [review]
Just a comment, the line symbol on tool type have two colors.
By example, on gpx, the Line symbol is red and white, while it should be only red.

**Comment by zarov** [comment]
Well seen, updated

**Review by gchoqueux — APPROVED** [review]

**Pull request merged**
