### PR TITLE
chore(example): rewrite the index page of examples

### PR DESCRIPTION
**Pull request by zarov**
Move to a look closer to the documentation one, to avoid having multiple
tabs opened every time we click on an example. Remove all screenshots as
they are no longer needed.

Please note that in a next commit, examples will be rearranged by
categories, like:
- View: globe, planar, immersive...
- Source / Stream: WMS, WMTS, TMS, WFS...
- Source / File: Geojson, GPX, KML, Shapefile...
- Source / Other: Mesh, Pointcloud...
- Plugins
- and so on

It looks like this for the moment
image

### CODE REVIEW

**Review by gchoqueux — COMMENTED** [review]
Very well, I'm waiting categories.
Autodeploy could be changed?

It would be necessary to change title example, to be more compact and explicit.
By example:

- Orthographic => classic 2d Map
- Pointcloud => point cloud viewer
- Pointcloud on globe => Add point cloud on globe
- Planar mode => 3D Map in metric projection
- Globe
     - basic
     - Multiple globes => 2 Globes
- Oriented images =>???
- Post processing
- WFS data with reprojection => WFS source
- 3d tiles
     - 3d tiles => basic 
     - 3D Tiles batch table hierarchy extension => batch table
- Layer visibility => Check ColorLayer visibility
- Splitted rendering
- Layers transformations => Cube maps
- Gpx => load Gpx
- Position a mesh => add mesh dmt
- globe with data vector => vector data to ColorLayer
- Plane mode with data vector => vector data to ColorLayer
- WFS extruded on globe => WFS/geojson to meshes
- Stereo effects
- Immersive - Paris
- 3D model loader
- Globe with vector tiles data => vector tiles on globe
- Plane mode with vector tiles data => vector tiles
- camera's animations with CameraUtils => Travel on Map
- synchronisation cameras with CameraUtils => Compare 2 Maps
- wfs source to color layer 
- geojson to geometry layer => geojson to mesh
- geojson with multipolygon as a geometry => geojson to mesh
- Orientation utils => ???
- Orientation utils planar => ???
- Displaying shapefile as a color layer => shapefile to color layer

**Comment by zarov** [comment]
> Autodeploy could be changed?

To what ?

Here's the menu I'm proposing, with the deletion of some examples:


- View
    - globe => 3D map
    - Planar mode => 2.5D map
    - Orthographic => 2D map
    - Multiple globes => Multiple globes
    - Layers transformations => Multiple 2.5D maps
    - Immersive - Paris => Immersive view

- 3d Tiles
    - 3d tiles => Basic
    - 3D Tiles batch table hierarchy extension => Batch table

- Pointcloud
    - Pointcloud => 2.5D map
    - Pointcloud on globe => 3D map

- Vector tiles
    - globe with vector tiles data => Raster on 3D map
    - Plane mode with vector tiles data => Raster on 2D map

- Source / Stream
    - WFS data with reprojection => WFS to 2.5D objects
    - WFS extruded on globe => WFS to 3D objects
    - wfs source to color layer => WFS to raster

- Source / File
    - Gpx => GPX to 3D objects
    - geojson with multipolygon as a geometry => GeoJSON to 3D objects
    - Displaying shapefile as a color layer => Shapefile to raster
    - globe with data vector => to split in 3 examples, geojson, gpx and kml:
        - GeoJSON to raster
        - GPX to raster
        - KML to raster

- Effects
    - Post processing
    - Splitted rendering
    - Stereo effects

- Miscellaneous
    - Layer visibility => Check ColorLayer visibility
    - 3D model loader => Collada
    - Position a mesh => Clamp 3d object to ground
    - camera's animations with CameraUtils => Camera animation
    - synchronisation cameras with CameraUtils => Compare 2.5D and 3D maps
    - Oriented image => Georeferenced image

- TO DELETE
    - Orientation utils
    - Orientation utils planar
    - Plane mode with data vector => to mix with globe with data vector
    - geojson to geometry layer

**Comment by zarov** [comment]
So I updated the PR, it is becoming big as I have renamed all the examples files, as well as functional testing files.

**Review by gchoqueux — APPROVED** [review]
doesn't forget to squash the commit

**Comment by nosy-b** [comment]
@zarov Well done!

**Pull request merged**
