### PR TITLE
changed singleton implementation (not ready)

### PR DESCRIPTION
**Pull request by vmora**
I have a problem with RequireJS in this code, so this PR is not meant to be merged, but is here for comment.

in relation to #33

The init functions have been removed and replaced by the ctor

The singleton implementation follows this recommendation:
http://stackoverflow.com/questions/1635800/javascript-best-singleton-pattern

A die() function has been introduced to throw Error, it is especially
usefull to test for mandatory arguments, e.g.:

this.__whaterver = mantatory_argument || die("mantatory_argument is mandatory");

### CODE REVIEW

**Comment by tbroyer** [comment]
Conceptually, I have a problem with singletons that have dependencies. This can be seen in your "constructors"

Also, the singleton-pattern is evil and we all know it; there's nothing wrong with objects being instantiated only once during the lifetime of an application, but that shouldn't mean using _global state_ (global state is possibly OK within an application, but not in a library, and iTowns aims at being a library).

My rules of thumb: http://misko.hevery.com/code-reviewers-guide/ (this guide is written with C++ and Java in mind, but applies just as well to any other language; Miško's blog is full of gems too, you'll also notice in Flaw # 1 the note about the constructor vs. `init()` that we talked about at the code sprint and you fixed here) Specifically here: http://misko.hevery.com/code-reviewers-guide/flaw-brittle-global-state-singletons/

Simple test: how would I use iTowns twice on the same page?
(imagine, coordinating the movement in 2 instances, either using different data or configuration –e.g. one with pointclouds only, the other with images– or different camera angles –e.g. the iTowns 1 demo with a front a rear views–)

IMO, the singleton pattern as seen here is a smell of a broader design issue. Let's try to fix that first (dependency injection vs. global state or service locator)

**Comment by vmora** [comment]
> Also, the singleton-pattern is evil and we all know it

Agreed, I'm not sure why, in the global design, those classes need to be singletons.

> http://misko.hevery.com/code-reviewers-guide/

Thanks for the reading, but I find that those "Warning Signs" are somewhat contradictory:

> Anything more than field assignment in constructors
> Object not fully initialized after the constructor finishes (watch out for initialize methods)

or are they pointing to factories whenever object need real work to be fully initialized ?

..yes they are, so I do agree.

**Comment by gchoqueux** [comment]
This branch is ready or not?

**Comment by tbroyer** [comment]
No, not at all. Let's close it for now, @vmora will eventually reopen it when he updates his branch (which might be never)

**Comment by vmora** [comment]
No problem.

Some of the stuff in there might be useful though. I like the `die` function that is used for mandatory arguments.

Concerning the singletons: I fully aggree with tbroyer, they should dissapear.

**Comment by gchoqueux** [comment]
[remove init singleton](https://github.com/iTowns/itowns2/commit/b657d2570219ec3d3b4d021530c97cb5de763db8)

**Pull request closed without merging**
