### PR TITLE
feat(controls): add state controls at view init

### PR DESCRIPTION
**Pull request by AnthonyGlt**
## Description
Add possibility to define the controls at the view initialization

## Motivation and Context
The controls can be redefined afterwards already but I wondered why it couldn't be at the init

### CODE REVIEW

**Comment by Desplandis** [comment]
There is already a lot of options in `GlobeView` but why not?
@mgermerie What do you think?

@AnthonyGlt Could please document it too in `GlobeView`?

**Comment by AnthonyGlt** [comment]
There is already:
```js

@param {Object} [options.controls] - See options of {@link GlobeControls}

``` 
in GlobeView

Should I also add :
```js
@param {StateControl~State} [options.controls.stateControl] redefining which controls state is triggered by the keyboard/mouse
event (For example, rewrite the PAN movement to be triggered with the 'left' mouseButton instead of 'right'

```
 ?

**Comment by Desplandis** [comment]
Yeah you're right, this is not correctly typed for now... At least there is a link to `GlobeControls`, so you can ignore my previous comment. =)

**Review by Desplandis — APPROVED** [review]

**Review by mgermerie — APPROVED** [review]
:+1:

**Pull request merged**
