### PR TITLE
fix (core): don't update non ready layers

### LINKED ISSUE #567: Blocking tile's subdivision after adding a raster layer
## Context
In globe example, if we add raster layer after initialization, some tiles stop to subdivide.

## Steps to Reproduce (for bugs)

1. load globe example
2. in console call
```js
globeView.controls.setCameraTargetGeoPosition({ longitude:  6.5, latitude:  46, range: 333000});
```
3. in console call
```js
globeView.addLayer({
    type: 'color',
    url: 'https://raw.githubusercontent.com/iTowns/iTowns2-sample-data/master/croquis.kml',
    protocol: 'rasterizer',
    id: 'Kml',
    name: 'kml',
})
```
4. in console call (he noted that this step should not be necessary)
```js
globeView.controls.setCameraTargetGeoPosition({ longitude:  6.5, latitude:  46, range: 330000});
```

## Possible Cause/Fix/Solution
the bug appears in commit e3db2308f3cca7f6eaa17f68779d48909d92339c

this [line](https://github.com/iTowns/itowns/commit/e3db2308f3cca7f6eaa17f68779d48909d92339c#diff-ad71c3a479d08240c3053171dd65d576R155) seems to be the origin of the bug

`layer.noTextureParentOutsideLimit` and `layerUpdateState` can cause the problem

### PR DESCRIPTION
**Pull request by peppsac**
We already do this for GeometryLayer and it's needed for other layers as well.

Fixes #567

### CODE REVIEW

**Comment by gchoqueux** [comment]
I pushed a suggestion on the branch

**Comment by peppsac** [comment]
@gchoqueux PR ready (I've squashed your commit in the first one)

**Comment by gchoqueux** [comment]
thanks, I forgot to test `!c.ready` for `elevationLayers` in `subdivisionControls.js`

**Comment by peppsac** [comment]
Updated.
Can you confirm that this PR fixes issue #567?

**Review by gchoqueux — APPROVED** [review]
it's fixed
Thanks

**Pull request merged**
