### PR TITLE
updated THREE to r87

### PR DESCRIPTION
**Pull request by nosy-b**
## Description
Updated THREE to r87

## Motivation and Context
Up to date as the 15th of September to the last THREE JS revision
 No problem running all examples.

### CODE REVIEW

**Comment by autra** [comment]
@nosy-b did you check https://github.com/mrdoob/three.js/releases for incompatible change?

**Comment by autra** [comment]
@Jeremy-Gaillard new version of three removed Gltf 1.0 support and renamed GLTF2Loader to GLTFLoader. Do we replace the loader we committed in itowns according to you?

**Comment by nosy-b** [comment]
@autra Yes, didn't see anything worrying.

**Comment by autra** [comment]
@nosy-b yep. Just the one thing about gltf loader, but I guess it could be done later.

**Review by autra — APPROVED** [review]

**Comment by Jeremy-Gaillard** [comment]
@autra the current 3D Tiles specification still references glTF 1.0 and all the 3D Tiles samples (which are used in our example) still use it. For now, we can't replace the glTF Loader, we may even need to keep it for a while until 3D Tiles-related tools are updated.

**Pull request merged**
