### PR TITLE
fix(examples): bad orthographic origin

### PR DESCRIPTION
**Pull request by zarov**
Forgot to change the origin from `bottom` to `top` in the orthographic example, sorry about that.

See #639

### CODE REVIEW

**Review by peppsac — COMMENTED** [review]
Can you add this in `TMS_Provider.prototype.preprocessDataLayer`  as well:
```js
layer.origin = layer.origin || (layer.protocol == 'xyz' ? 'top' : 'bottom');
```
And then remove the `origin` declaration in `orthographic.js`

**Comment by zarov** [comment]
The protocol `xyz` has been removed in the other PR, do you want to add it back ?

**Comment by peppsac** [comment]
Oh. I misread the code yesterday when I approved... Yes I would prefer to keep the 2 protocol names + the `origin` option. Sorry.

**Comment by zarov** [comment]
OK, fixed

**Review by peppsac — APPROVED** [review]
Thanks!

**Pull request merged**
