### PR TITLE
feat(core): update to THREE v89

### PR DESCRIPTION
**Pull request by gchoqueux**
## Description
Update to THREE v89, with validation that nothing is breaking

## Motivation and Context
need in PR #629 , #626, #631, #634

### CODE REVIEW

**Review by peppsac — CHANGES_REQUESTED** [review]
Nope.

We can't jump 2 versions of three.js without a review of the changes.

Did you review the release notes for v0.88 and v0.89?
Did you check what breaking changes could affect us?
Or if any new features would be helpful?

Quick example with 1 change:
```
    Added decodeText() static method and implemented in all loaders. #12654 (@donmccurdy)
```
Which could allow us to drop the `text-encoding-utf-8` dependency.

**Comment by gchoqueux** [comment]
Yes of course, I read the reviews
In THREE.js's working methods, they passe the break changes in **deprecated**
By example, [AxesHelper](https://github.com/iTowns/itowns/pull/630/files#diff-df61a67eee71572718ef066564a3a0afR258), the change was reflected in itowns and deprecate in THREE ([here](https://github.com/mrdoob/three.js/pull/12321/files#diff-697749014a2009c4ea9c6741f042c804R306)). 
Except this one, I think there's no other break change

There are still efforts to make the most of the THREE's features. (Some are in PR #629 , #626)

I push a commit to replace  `text-encoding-utf-8`, but I'm not sure of their implementation that instantiates a `DecodeText` to use, see [here](https://github.com/mrdoob/three.js/pull/12654/files#diff-75041da7958590b0bd3002b909522af0R7). it goes against the efforts made in this commit dc4c41d5

**Comment by peppsac** [comment]
And what about:
```
    Replaced triangulator code with Earcut. #12661 #12725 (@Mugen87)
```
We're using `earcut` as well so it's probably an opportunity to get rid of this dependency (or to explicitely state in the commit message why we don't want to do this).

**Comment by gchoqueux** [comment]
I add in the commit message : `TODO try the new earcut in three v89` see #631

and 9cc4f57 you really want this change?

**Comment by peppsac** [comment]
> I add in the commit message : TODO try the new earcut in three v89 see #631

I hoped that you could integrate it in this PR since it's probably a 1 line change in Feature2Mesh.js

> and 9cc4f57 you really want this change?

I think so. But I'd love to have some context: for instance did you check the itowns.js bundle size to see if removing the dependency had a measurable effect?

**Comment by gchoqueux** [comment]
This PR was created to facilitate the review and separate the refactos needed in other PRs. (#629 , #626 #634). In this sense I moved the decode text refacto in #634.
This PR is an update of three.js with a check if nothing is breaking.
it need a new PR for the EarCut, for the re-factoring, the test of this new feature and the reviewing (a issue is open #631)

**Review by peppsac — APPROVED** [review]
OK, let's split the upgrades on new threejs feature to other PRs.

**Pull request merged**
