### PR TITLE
refactor (vector): deleting an unnecessary double key properties geojson parsing

### PR DESCRIPTION
**Pull request by gchoqueux**
## Description
all  feature's properties are combined into one object

##
I take the opportunity to rename `GeoJSON2Feature` to `GeoJSON2Features`

### CODE REVIEW

**Comment by gchoqueux** [comment]
Warning to PR #470 and #519 
This PR impacts you

**Review by peppsac — COMMENTED** [review]
Looks OK.
Could you adapt your commit messages to the convention described in https://github.com/iTowns/itowns/issues/518 ?

(feel free to comment in this issue too)

**Comment by gchoqueux** [comment]
updated @peppsac

**Review by peppsac — APPROVED** [review]
Thanks!

**Pull request merged**
