### PR TITLE
Preparation to serialization of Extent and Feature

### PR DESCRIPTION
**Pull request by ftoromanoff**
## Description
Some minor changes to prepare for the serialisation of itowns.objects:

- Extent() add a new static method for the caclulation of the intersection between 2 extents.
- Style() minor change for when document doesn't exist
## Motivation and Context
To prepare for the following improvment:
- rework on Style
- dynamic properties of Source
- preparation for workerisation

### CODE REVIEW

**Comment by alexLuky** [comment]
@ftoromanoff 
what is the main benefit of the workerization? Is it for performance render boost?

**Comment by ftoromanoff** [comment]
> @ftoromanoff what is the main benefit of the workerization? Is it for performance render boost?

During the investigation for workerisation, several other issues came to mind. This PR and the following will focus and these more than workerisation.
The thought about workerisation is indeed to get higher performance but it's currently still in reflexion.

**Comment by jailln** [comment]
Ok for me, could you just rename the commit a little bit please? : 
```
refacto(FeatureGeometryLayer): cleanup -> remove extra line 

refactor(Extent): move intersectsExtent to static Extent.intersectsExtent(ExtentA,ExtentB)=

[refactor(Style): change on var canvas for workers
```

**Comment by jailln** [comment]
Thanks but you need to use one of `refacto`, `refactor` or `refactoring` for the automatic changelog to work (see [here](https://github.com/iTowns/itowns/blob/master/config/conventionalChangelog/config.js#L66), could you update please ?

**Comment by ftoromanoff** [comment]
> Thanks but you need to use one of `refacto`, `refactor` or `refactoring` for the automatic changelog to work (see [here](https://github.com/iTowns/itowns/blob/master/config/conventionalChangelog/config.js#L66), could you update please ?

In my head refact was there as well ^^
Sorry, I will correct that right away

Ii also tried to be a bit more clear about the message but if it's not just tell me.

**Comment by jailln** [comment]
> > Thanks but you need to use one of `refacto`, `refactor` or `refactoring` for the automatic changelog to work (see [here](https://github.com/iTowns/itowns/blob/master/config/conventionalChangelog/config.js#L66), could you update please ?
> 
> In my head refact was there as well ^^ Sorry, I will correct that right away

No problem :) Or you can add it to the list, as you wish ^^

**Review by jailln — APPROVED** [review]

**Pull request merged**
