### PR TITLE
fix (protocol) : stop using layer's options tileMatrixSet in WMS provider

### PR DESCRIPTION
**Pull request by gchoqueux**
WMS layer haven't tileMatrixSet, this PR removes this inconsistency

problem when you use PR #513

### CODE REVIEW

**Review by peppsac — COMMENTED** [review]
Commit message should be `fix (protocols)` (not `protocol`).

Also `fix the undef layer...` is unclear.
Here's another wording, which seems clearer to me:
```
fix (protocols): stop using tileMatrixSet for WMS protocol

tileMatrixSet are only valid for WMTS protocol so the WMS_Provider can't use them (because they will probably be undefined)
```

**Comment by gchoqueux** [comment]
ok, I change message
`tileMatrixSet`  is valid for `wms`, it's projection that determines its `tileMatrixSet`

**Comment by peppsac** [comment]
`TileMatrixSet` is missing from the WMS spec (http://www.opengeospatial.org/standards/wms) so I don't see what link do you see between tilematrixset and wms?

**Comment by gchoqueux** [comment]
in itowns, the `wms` uses the wmts's tile matrix set.

**Comment by peppsac** [comment]
Looks more like a bug than a feature to me; mainly because WMTS / TileMatrixSet only makes sense for the globe.

**Comment by gchoqueux** [comment]
i don't understand

**Comment by peppsac** [comment]
Don't you think that:

> in itowns, the wms uses the wmts's tile matrix set.

And:

> WMS layer haven't tileMatrixSet, this PR removes this inconsistency

are a bit contradictory?

And can you explain to me how WMTS TileMatrixSet are going to help when using WMS on a planar geometry (for instance: drawing a `EPSG:3857` layer on a `EPSG:3946` geometry)?

**Comment by Mkonini** [comment]
@gchoqueux , @peppsac 
To facilitate understanding maybe it would be better to open an issue to discuss about, and btw see if the proposed fix is worthly to be merged.

**Comment by zarov** [comment]
@gchoqueux could you explain where the WMS uses the `tileMatrixSet` of the WMTS in iTowns ? So we can better understand it, as this PR should be merged by now.

**Comment by gchoqueux** [comment]
In [wms_provider](https://github.com/iTowns/itowns/blob/a616629d9001a6a988b40598cd4575c60372fbd9/src/Core/Scheduler/Providers/WMS_Provider.js#L135)  the wms texture is branded by tile's coord. it corresponds to the tile matrix set. this allows us to know if the texture is accurate enough for the tile. 

On the other hand this PR stops to use tileMatrix set in layer's option.

**Review by peppsac — COMMENTED** [review]
Rebasing / force-pushing the PR makes the conversation useless because the matching code changes aren't accessible now.

Anyway, this PR looks good now.

**Review by zarov — APPROVED** [review]

**Comment by zarov** [comment]
Thanks @gchoqueux and @peppsac

**Pull request merged**
