### PR TITLE
Build using webpack, getting dependencies with NPM

### PR DESCRIPTION
**Pull request by tbroyer**
Notable changes:
- Replace src/ThirdParty/ entirely with NPM dependencies
- Replace many src/Renderer/Three/ and src/Renderer/ThreeExtented
  scripts with scripts coming right from the Three.js module.
  Those are a bit hackish though, as they modify the THREE object;
  use with care.
- Make all implicit dependencies on Three.js explicit by adding a
  
  ```
  var THREE = require('three');
  ```
  
  at the top of the files, or adding 'three' to the AMD dependencies.
- Add aliases in Webpack to avoid rewriting many dependencies.
  Cleanup will be done in a forthcoming change.
- Replace require-text with Webpack's raw-loader. This is configured
  as a rule for all *.glsl files, rather than on each import.
- src/Renderer/Utils.js won't work as it "depends" on a "Cartography"
  module that doesn't exist. The import has been moved to the top of
  the file, but commented so that Webpack doesn't complain.

### CODE REVIEW

**Comment by Jeremy-Gaillard** [comment]
Works here.
I just have this warning when running npm start:  
WARNING in ./~/js-priority-queue/priority-queue.js
Critical dependencies:
1:486-493 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/js-priority-queue/priority-queue.js 1:486-493

I'm in favour of merging as soon as possible.

**Comment by tbroyer** [comment]
The warning is due to webpack/webpack#1617

We could:
- ask Webpack to add a way to opt-out (already done in issue linked above)
- ask js-priority-queue to change the way CoffeeScript is transpiled to JS and deploy non-browserified transpiled JS to the NPM registry
- live with it

**Comment by tbroyer** [comment]
I also just js-beautified everything (using the default js-beautify config), which happens to be close to what we're using.
amdtoes6 branch still needs to be rebased (working on it)

**Comment by nosy-b** [comment]
@tbroyer On windows seems to bug after npm install and build:
Uncaught ReferenceError: THREE is not defined
Uncaught ReferenceError: itowns is not defined
Ideas?

**Comment by tbroyer** [comment]
@nosy-b Will have a look (not before tomorrow though)
Do you have more context around those lines? Also, which version of Node.js are you using?

**Comment by nosy-b** [comment]
(The build worked fine in V1)

**Comment by nosy-b** [comment]
I checked and updated npm, still bug

**Comment by nosy-b** [comment]
The npm install log:
$ npm install
npm WARN optional Skipping failed optional dependency /webpack/watchpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7

**Comment by nosy-b** [comment]
Build tested on mac, no problem. It's just on win

**Comment by tbroyer** [comment]
OK, reproduced in a Windows VM. Seems to be related to those f***ing `\` path separators.

Apparently, changing the following line in `webpack.config.js`:

``` js
        test: /node_modules\/three\/examples\/.*\.js$/,
```

to

``` js
        test: /node_modules[\\/]three[\\/]examples[\\/].*\.js$/,
```

fixes it in my VM.

Could you try that and report the result here? I'll commit and push that fix if it works for you.

**Comment by nosy-b** [comment]
That works now! Classic f**\* problem yes :)

**Comment by gchoqueux** [comment]
I would like use this dependence [https://github.com/mrdoob/three.js/tree/dev](url)
how to do?

**Comment by tbroyer** [comment]
@nosy-b Pushed as e2c5cde27414d458b359130171ed1bd75f603a7e

@gchoqueux Try updating `three` to use their Git repo:

```
npm install --save three@git+https://github.com/mrdoob/three.js.git#dev
```

(not tested, and I have a meeting right now; if that command doesn't work, try updating the `package.json` instead: https://docs.npmjs.com/files/package.json#git-urls-as-dependencies and running `npm install` again)

**Comment by tbroyer** [comment]
@gchoqueux OK, so, started looking at it in more details, and it would be a bit more change than just switching the version (see https://github.com/mrdoob/three.js/issues/8071#issuecomment-185710709), but hopefully not that big a change either.

That said, given that (almost) each version of Three.js contains breaking changes, we'd probably better anchoring to a specific commit rather than just referencing the `dev` branch.

**Comment by tbroyer** [comment]
@gchoqueux Have a look at the `three.js-dev` branch.
Should we merge it to `master`?

**Pull request merged**
