### PR TITLE
Release v2.4.0.

### PR DESCRIPTION
**Pull request by gchoqueux**
## Description
New release
Change log coming soon

### CODE REVIEW

**Review by zarov — APPROVED** [review]
:tada:

**Comment by nosy-b** [comment]
@zarov That was fast :)
Everything seems to work fine, some better than before, congrats!
An error though, while testing from scratch on Win7 with npm install:
```
public_html\ios\itowns\node_modules\semver\semver.js:678
    throw new TypeError('Invalid comparator: ' + comp);
    ^

TypeError: Invalid comparator: '
    at Comparator.parse (D:\public_html\ios\itowns\node_modules\semver\semver.js:678:11)
    at new Comparator (D:\public_html\ios\itowns\node_modules\semver\semver.js:662:8)
    at D:\public_html\ios\itowns\node_modules\semver\semver.js:780:12
    at Array.map (native)
    at Range.parseRange (D:\public_html\ios\itowns\node_modules\semver\semver.js:779:13)
    at Range.<anonymous> (D:\public_html\ios\itowns\node_modules\semver\semver.js:721:17)
    at Array.map (native)
    at new Range (D:\public_html\ios\itowns\node_modules\semver\semver.js:720:40)
    at D:\public_html\ios\itowns\node_modules\check-node-version\index.js:119:32
    at module.exports (D:\public_html\ios\itowns\node_modules\map-values\index.js:9:18)
```

**Comment by gchoqueux** [comment]
it is the same issue #868, no?

**Comment by nosy-b** [comment]
I got the same message as #868 yes which is not important but the TypeError does hurt more the eyes ;)

**Comment by nosy-b** [comment]
Ok, commenting the line "prepare" in package.json do the trick.
Let's remove it on the next 2.4.1!

**Pull request merged**
