### PR TITLE
feat(protocols): replace text-encoding-utf-8 module by THREE.LoaderUtils.decodeText

### PR DESCRIPTION
**Pull request by gchoqueux**
## Description
Replace `text-encoding-utf-8` module by `THREE.LoaderUtils.decodeText`

## Motivation and Context
Remove module  `text-encoding-utf-8`

### CODE REVIEW

**Comment by zarov** [comment]
@gchoqueux can you rebase this PR ? Thanks

**Comment by Jeremy-Gaillard** [comment]
Updated.

**Comment by peppsac** [comment]
Currently three.js creates a new `TextDecoder` each time you ease the `decodeText` method (see https://github.com/mrdoob/three.js/blob/dev/src/loaders/LoaderUtils.js#L7) so maybe we don't want to merge this PR.

**Comment by gchoqueux** [comment]
replace by #698

**Pull request closed without merging**
