### PR TITLE
feature(3dtile): support rtc center from feature.

### PR DESCRIPTION
**Pull request by gchoqueux**
## Description
Add support of rtc center from feature table.

### CODE REVIEW

**Review by zarov — APPROVED** [review]
LGTM. 

@jailln I don't remember, but do you plan to add support to feature table ? I'm asking since you (and I'm very grateful for that) did the recent 3dtiles cleaning.

**Comment by jailln** [comment]
@zarov I don't plan to add it for now; however this PR might be a good opportunity to introduce it as the feature table for b3dm is only composed of two attributes: RTC_CENTER and BATCH_LENGTH (see [this json schema](https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/specification/schema/b3dm.featureTable.schema.json)) ?

**Comment by zarov** [comment]
Oh I say why not then. @gchoqueux can you do that in this PR if it doesn't take too much time ?

**Comment by gchoqueux** [comment]
`BATCH_LENGTH` support added.

**Review by zarov — APPROVED** [review]
LGTM, thanks for this !

**Pull request merged**
