### PR TITLE
Md fix

### PR DESCRIPTION
**Pull request by autra**
Here are some MD updates + templates for PRs and issues. 

@iTowns/reviewers please r?

### CODE REVIEW

**Comment by Jeremy-Gaillard** [comment]
I pushed a few fixes.

You mention a CHANGES.md file that does not exist, either create it or remove reference to it in CONTRIBUTING.md

**Comment by autra** [comment]
> You mention a CHANGES.md file that does not exist, either create it or remove reference to it in CONTRIBUTING.md

Ok, let's remove it. This actually raises a question: how to we deal with bug corrections and associated release? I can maintain a 2.0.x branch and periodically release a patch version on npm, but we might want to formalize this workflow a bit. Unrelated to the current PR though.

**Comment by autra** [comment]
updated.

**Review by peppsac — APPROVED** [review]

**Comment by autra** [comment]
For reference, the templates have been generated with https://www.talater.com/open-source-templates/#/

**Comment by peppsac** [comment]
I propose merging the PR as it originally was (`.md fix`) and move the template stuff to another PR.
WDYT?

**Comment by autra** [comment]
Agreed, moving this right now.

**Comment by autra** [comment]
Updated. Only fixes in this PR now.

**Pull request merged**
