### PR TITLE
fix(protocols): respect the order of the file features to draw texture

### PR DESCRIPTION
**Pull request by gchoqueux**
## Description
Respect the order of the file features to draw texture

### CODE REVIEW

**Review by peppsac — CHANGES_REQUESTED** [review]
Looks more like a hack than a fix to me (it will "fix" the problem on one file and break other files).
If you want a simple fix, you can probably allow to specify `globalCompositeOperation` in the `style` properties instead.

**Comment by mbredif** [comment]
Would you agree on having a `style` property that defaults to `'destination-over'` ?

**Comment by peppsac** [comment]
> Would you agree on having a style property that defaults to 'destination-over' ?

Yep

**Comment by gchoqueux** [comment]
done

**Review by peppsac — APPROVED** [review]

**Pull request merged**
