### PR TITLE
3D Tiles on 2.5D map

### PR DESCRIPTION
**Pull request by jailln**
## Description
This is a followup of PR #1034. 
Since I won't have time to apply the process you suggested to reduce the size of the tiles, I use a smaller dataset in this PR (only the 1st borough of Lyon). 

## Motivation and Context
I think it would be useful to have an example of 3D Tiles on plane in the codebase of iTowns. It demonstrates this capability and it is useful for us (and other people working with 3D Tiles on a planar view of itowns in their projects) for debugging purposes.

## Screenshots (if appropriate)

image

### CODE REVIEW

**Comment by gchoqueux** [comment]
Thanks, for this example.
The b3dm file size are too heavy (`~3.6/5.5 MB`)

**Comment by jailln** [comment]
Why is it a problem since the dataset is not from itowns but an external source ?

**Comment by gchoqueux** [comment]
Yes indeed, but when I tested the demo, the 3d tiles took a long time to load and I thought there was a performance issue in itowns.

**Comment by jailln** [comment]
Ok, unfortunatly I won't have time to work on reducing their size. Would you have time to apply the process you mentionned in #1034 to this dataset ? (or to give more specific instruction so I can apply it?). Otherwise I think we can close this PR.

**Comment by gchoqueux** [comment]
Yes, I understand. I'll look into ways to quickly convert this data.

**Comment by jailln** [comment]
Nice, thanks! Let me know if I can help.

**Comment by gchoqueux** [comment]
### Options to lighten the b3dm file size
#### During mesh construction
* avoid to create a vertex for a face if any are already in the same position (use face index list).
* avoid to have more than 2 vertices to define a segment.
* avoid to build faces under the building because they will hidden by the ground.
* avoid to compute face normals.
#### The above options can also be applied with a optimization mesh tools 
* merge all vertices with the same position.
* merge all adjacent faces with a angle of 0.
* delete face normals.
#### Convert mesh to `glTF`
* doesn't export normals face.
* use Draco compression.
#### If you have already generated the `glTF`
* converting a `glTF` to `Draco glTF` [glTF-pipeline](https://github.com/CesiumGS/gltf-pipeline#converting-a-gltf-to-draco-gltf)
#### If you have already generated the `b3dm`
* apply draco with [optimizeB3dm](https://github.com/CesiumGS/3d-tiles-validator/tree/master/tools#optimizeb3dm) unfortunately it doesn't work if the embedded `glTF` is in version 2.0.
* if `glTF` is in version 2.0, creates a `glb` from a `b3dm` with [b3dmToGlb](https://github.com/CesiumGS/3d-tiles-validator/tree/master/tools#b3dmtoglb) and apply Draco with [glTF-pipeline](https://github.com/CesiumGS/gltf-pipeline#converting-a-gltf-to-draco-gltf)

**This last option could the short way to optimize yours `b3dm` files.**

I had written a wiki page [advices for generating small glTF files](https://github.com/iTowns/itowns/wiki/3D-Tiles#advices-for-generating-small-gltf-files).

**Comment by jailln** [comment]
Thanks for these propositions! I applied draco compression (from the second process you suggested since our b3dm files are in gltf 2.0 version) and it greatly reduces the size of the b3dm files. However, the batch table (and therefore the semantic information) is lost during this process, so I removed the picking from the example.
Let me know if it's ok on your side; then I'll squash some commits and rebase on master.

**Review by gchoqueux — APPROVED** [review]
Nice!
I've noticed that b3dms are loaded several times as soon as they switch from invisible to visible. We should adjust the cache management.

**Comment by gchoqueux** [comment]
@jailln Could you squash the commits?

**Comment by jailln** [comment]
Squashed and rebased on master!

> I've noticed that b3dms are loaded several times as soon as they switch from invisible to visible. We should adjust the cache management.

Yes, I already opened issue #1170 on this subject

**Pull request merged**
