### PR TITLE
fix(controls): focus on the viewer div after view creation

### PR DESCRIPTION
**Pull request by zarov**
So I got in a use case similar to #81, so here's a fix !

### CODE REVIEW

**Comment by zarov** [comment]
I fixed the error in CI by pushing a new commit on bad `View` and `GlobeView` calling.

**Review by gchoqueux — APPROVED** [review]

**Comment by gchoqueux** [comment]
and if viewer loses focus?

**Comment by zarov** [comment]
Unfortunately we can't cover all situations, so I don't know. I trust that people using iTowns handle this situation themselves.

**Comment by gchoqueux** [comment]
ok

**Pull request merged**
