### PR TITLE
feat(crs): add the support of WKT with proj4

### PR DESCRIPTION
**Pull request by zarov**

### CODE REVIEW

**Comment by gchoqueux** [comment]
Proj4 is exported in itowns ?
If proj4 is exported, It's already possible to add proj4 definition ?

**Comment by zarov** [comment]
It is indeed, I thought it was easier to have this wrapper instead of doing `itowns.proj4` ?

**Review by gchoqueux — COMMENTED** [review]
Between
`itowns.CRS.registerWKT(name, wkt)`
and
`itowns.proj4.defs(name, wtk)`
I prefer the last because is more explicit

**Comment by zarov** [comment]
Ok, no problem !

**Pull request closed without merging**
